### ISSUE TITLE
Cordova v9.0.0 no longer uses plugins in the config.xml – not reflected in docs

### ISSUE THREAD

**Issue by ryanmtaylor** [apache/cordova-docs#1004]
Cordova 9.0.0 no longer uses config.xml as the source of plugin (or platform) data/versions.

This is mentioned in the release notes and links to here: https://github.com/apache/cordova-lib/pull/750 however I could not find this documented _anywhere_ else.

Specifically, the config.xml documentation at https://cordova.apache.org/docs/en/latest/config_ref/#plugin does not mention it.  Again, I literally only found it mentioned briefly in the release notes here: https://cordova.apache.org/announcements/2019/03/18/cordova-lib-release-9.0.0.html

Thank you

**Comment by janpio** [comment]
For plugins this is not actually true. 

I ran `cordova platform add android` on a Phonegap Build project that only has `www` and `config.xml`:

```
C:\Users\Jan\Downloads\tt (master -> origin)
λ ls
config.xml  www/

C:\Users\Jan\Downloads\tt (master -> origin)
λ cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.foo.android
        Name: foo
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-email-composer' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-googlemaps' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Discovered saved plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for android
Adding cordova-plugin-statusbar to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "cordova-plugin-email-composer". Adding it to the project
Installing "cordova-plugin-email-composer" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-email-composer to package.json
Discovered saved plugin "cordova-plugin-googlemaps". Adding it to the project
Installing "cordova-plugin-googlemaps" for android
Failed to install 'cordova-plugin-googlemaps': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

C:\Users\Jan\Downloads\tt (master -> origin)
λ ls
config.xml  node_modules/  package.json  package-lock.json  platforms/  plugins/  www/

C:\Users\Jan\Downloads\tt (master -> origin)
λ cat package.json
{
  "devDependencies": {
    "cordova-plugin-email-composer": "^0.8.15",
    "cordova-plugin-googlemaps": "^2.4.6",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-email-composer": {},
      "cordova-plugin-googlemaps": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

Note how it recognized the plugins in `config.xml` and put them in `package.json` (which it also created from scratch).

**Comment by brodybits** [comment]
I would agree with @janpio. My understanding is that the Cordova tooling will still check for plugins in `config.xml` when you add a new platform or do `cordova prepare`. But this may be changed in an upcoming release. (I don’t remember where this was discussed, hope someone can find it.)

I think we should update the documentation as follows:

- add a note that this is a deprecated field in `config.xml` which has been superseded by configuration in `package.json`
- remove the outdated note that the element is added to `config.xml` when the `--save` flag is used
- ensure that the information about how Cordova uses and updates `package.json` is documented properly (I will raise a new issue for this point)

**Comment by dpogue** [comment]
As of the latest Cordova release (9.x):

* Platforms and Plugins are saved into package.json `dependencies` when they are added to a project
  * We’d like to move these to `devDependencies` instead in the next major
* `cordova prepare` will use the list of platforms/plugins from package.json as the canonical version
* If there are no platforms/plugins listed in package.json, and they exist in config.xml, `cordova prepare` will migrate them over to package.json

This is mostly the same behaviour as Cordova 8, except that we no longer add dependencies to config.xml under any circumstances.

**Comment by matt-auckland** [comment]
If Cordova is no longer generating `<platform>` tags, does this mean we need to add them in ourselves when specifying platform specific `<preference>`s or configuration tags? 
Or is there a way to do this configuration inside the `package.json`?

Are there plans to change this in the future?

**Comment by jacobg** [comment]
What can we safely remove from config.xml in order to clean it up? Can we delete all `<plugin>` elements? Anything else? e.g., `<engine>`?

**Comment by killroy42** [comment]
Where can I find how to use the config in package.json? Specifically the "build" key and how I can specify different elements for debug and release builds. A complete list of what configuration is possible here would be great too, or even the source file where I could figure it out.

**Comment by jfoclpf** [comment]
@killroy42 the plugins info (just code name and some settings) are in `package.json` under `cordova` property

```json
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {
        "GPS_REQUIRED": "true"
      },
      "cordova-plugin-statusbar": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-device": {},
      "cordova-plugin-whitelist": {},
```

the plugin versions are are also in `package.json`  under `dependencies` or `devDependencies`, such as any normal npm module

```json
 "dependencies": {
    "@fortawesome/fontawesome-free": "5.15.4",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.6.1",
    "cordova": "^10.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-import-npm": "^1.0.33",
    "cordova-pdf-generator": "^2.1.1",
    "cordova-plugin-app-version": "^0.1.12",
    "cordova-plugin-cache-clear": "^1.3.8",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-geolocation": "^4.1.0",
```

**But you don't need to worry about that**, when you install or remove a plugin everything is done for you

To install
```
cordova plugin add cordova-plugin-<name>
```
to remove
```
cordova plugin rm cordova-plugin-<name>
```

**Comment by jfoclpf** [comment]
as @dpogue mentioned
> * If there are no platforms/plugins listed in package.json, and they exist in config.xml, `cordova prepare` will migrate them over to package.json

@killroy42 you can then:
 - just do `cordova prepare` such that all plugins info will be moved/copied from  `config.xml` into `package.json`
 - then you can delete plugins info from `config.xml` if they're still there

**Comment by killroy42** [comment]
No, I mean the "build" key:
```
"build": {
		"compression": "maximum"
	},
```

**Comment by jacobg** [comment]
Can `<engine>` also be removed from config.xml?

**Comment by jfoclpf** [comment]
> Can `<engine>` also be removed from config.xml?

Yes! [Mine](https://github.com/jfoclpf/form-for-parking-violation/blob/master/config.xml) has not and it works fine.

But then you need to run `cordova platform add android|ios` when you initialize the project from scratch.

**Comment by jfoclpf** [comment]
@jacobg 

> Where can I find how to use the config in package.json? Specifically the "build" key and how I can specify different elements for debug and release builds. A complete list of what configuration is possible here would be great too, or even the source file where I could figure it out.

I don't know which key do you refer to, I don't find any in the documentation of [config.xml](https://cordova.apache.org/docs/en/10.x/config_ref/) and I don't have such key in `package.json` of my projects.

Regarding the difference between debug and production you build, compilte it or run it with the respective tag

```
cordova build android --release
cordova build android --debug

cordova compile android --release
cordova compile android --debug

cordova run android --release
cordova run android --debug
```

check the [docs of the CLI](https://cordova.apache.org/docs/en/10.x/reference/cordova-cli/) and the [docs](https://cordova.apache.org/docs/en/10.x/config_ref/) of `config.xml`

**Comment by jacobg** [comment]
@jfoclpf I didn't post that message. It was @killroy42

**Comment by jfoclpf** [comment]
BTW @killroy42 , if what you mean is to run some scripts or commands before or after build, compile or run, you have to use [hooks](https://cordova.apache.org/docs/en/10.x/guide/appdev/hooks/)

**Comment by jfoclpf** [comment]
@jacobg BTW, I assume your project uses the latest version of the platforms, otherwise it may be wise to let the `engine` in `config.xml` because it refers to a specific platform version

**Comment by jacobg** [comment]
@jfoclpf I assumed cordova is inferring versions from package.json. Is it not?
```
  "devDependencies": {
    "cordova-browser": "~6.0.0",
    "cordova-ios": "~6.2.0",
    "cordova-android": "~10.1.1",
```

**Comment by killroy42** [comment]
@jfoclpf That's kinda the point! It's not documented. It somehow controls the compression level of the zip process of the cordova-electron platform. But I have no idea how exactly it works or where I can look up how the info travels from the cordova package.json file on the "build" key, down into the platform, the node_module and the electron-builder sub process. 

All I am asking for are basic listings of all settings/configs somewhere.

**Comment by jfoclpf** [comment]
> @jfoclpf I assumed cordova is inferring versions from package.json. Is it not?
> 
> ```
>   "devDependencies": {
>     "cordova-browser": "~6.0.0",
>     "cordova-ios": "~6.2.0",
>     "cordova-android": "~10.1.1",
> ```

oh yes, that's true, you're right! They're added when you do `cordova platform add`

**Comment by jfoclpf** [comment]
> @jfoclpf That's kinda the point! It's not documented. It somehow controls the compression level of the zip process of the cordova-electron platform. But I have no idea how exactly it works or where I can look up how the info travels from the cordova package.json file on the "build" key, down into the platform, the node_module and the electron-builder sub process.
> 
> All I am asking for are basic listings of all settings/configs somewhere.

Ah ok, you're referring to `cordova-electron`, I thought you were referring to standard android and ios apps.

Cordova electron uses electron, the configuration for build you find here:
https://www.electron.build/configuration/configuration#overridable-per-platform-options

```
compression = normal “store” | “normal” | “maximum” - The compression level. If you want to rapidly test build, store can reduce build time significantly. maximum doesn’t lead to noticeable size difference, but increase build time.
```

**Comment by killroy42** [comment]
But the debug/release switching seems to be done at the cordova level, so electron-cordova doesn't know anything about it. I'm currently assuming it just isn't possible, short of changing the package.json file from a hook, but the documentation doesn't really clearly state this or fully document that schema. I understand it's not something easily solvable, but I often find myself several levels removed from stuff that happens, for example config files form the nested tools getting overwritten from a higher level tool (for example the builder-effective-config.yaml file), which mikes it hard to configure things and/or to know where and how to configure things.

Anyway, that's more a generic frustration, and not something I expect anybody can solve.

I've now published my game/app on iOS, Android, Steam and some other stores, which is amazing. But it also feels like it's all a tall house of cards with hardly any future proofing.
