### ISSUE TITLE
Windows platform guide is outdated

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#1006]
Webpage: <https://cordova.apache.org/docs/en/latest/guide/platforms/windows/index.html>

Source: <https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/platforms/windows/index.md>

- [x] Determine whether or not we are still supporting Windows 8.1 ~~(I thought we had already dropped Windows pre-10)~~
- ~~Remove all mention of Windows 8.1 host, Windows 8.1 target (assuming I am not mistaken)~~
- ~~ensure there is no mention of Windows Phone 7, 8, or 8.1~~
- [ ] explain that the developer must use VS 2017 ~~and no other version~~ _or VS 2015 (which is deprecated)_, along with link to apache/cordova-windows#327, as I proposed in apache/cordova-windows#355 (VS 2019 is definitely not supported as discussed in apache/cordova-windows#327; ~~now I am not sure about VS 2017~~. Any input from @janpio or others?)

**Comment by janpio** [comment]
You are mistaken, see https://github.com/apache/cordova-windows/pull/355#issuecomment-510803315

Your checkboxes 1 to 3 are invalid (and only Windows versions mentioned are 8.1 and 10).
Your checkbox 4 is already covered in https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/platforms/windows/index.md, which just hasn't been promoted to `lastest`.

So I think you could fix all that by promoting `dev` to `latest` in the docs and deploy the result.

**Comment by brodybits** [comment]
I updated the description accordingly.

> So I think you could fix all that by promoting `dev` to `latest` in the docs and deploy the result.

Any pointers would be appreciated. But I cannot promise when I will get a chance to do this.

**Comment by erisu** [comment]
Platform was deprecated. Docs removed in dev (next release).
