### ISSUE TITLE
Add StellarLibrary.com to the showcase

### ISSUE THREAD

**Issue by michaelpeterlee** [apache/cordova-docs#1023]
# Feature Request

Add Stellar to showcase an advanced application that uses Cordova!

## Motivation Behind Feature

Not self promotion, be assured! The Stellar cross-platform app suite showcases a large-scale, advanced application that demonstrates what you can do with the 'write once run anywhere' philosophy. I'm happy to supply an overview of the app for your website..

## Feature Description

Notifications, Offline-first encrypted file storage and synchronisation, iOS/Android. We also use Electron for MSWin and OSX.

**Comment by jcesarmobile** [comment]
Thanks for the issue, but we are actually planning on removing that section, so we won't be adding more apps to it.
