### ISSUE TITLE
Java requirement for cordova-android

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#1030]
https://lists.apache.org/thread.html/e7012d9efd1109db6be852ff09c83b7fd1ff1fbd9130cd03b7b06d3b%40%3Cdev.cordova.apache.org%3E

I think this needs to be investigated, tested, and documented.

/cc @jcesarmobile @breautek

**Comment by jcesarmobile** [comment]
Looks like gradlew commands try to run java internally, so I think we are good requiring Java 8.
