### ISSUE TITLE
Flash on cordova.apache.org?

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-docs#1031]
I just noticed Firefox is bringing a flash warning. Is Adobe Flash really necessary to use cordova.apache.org

![German for "This website uses Adobe Flash, Only alllow on trusted sites](https://user-images.githubusercontent.com/3585860/70626753-47ab5580-1c25-11ea-8582-05d6524a18e6.png)
(German for "This website uses Adobe Flash, Only alllow on trusted sites)

**Comment by timbru31** [comment]
Interesting. I couldn't trigger a warning regarding Flash on https://cordova.apache.org/blog/ - could you possibly investigate further which caused this?

**Comment by breautek** [comment]
I'm also unable to reproduce this. Perhaps its a browser addon?

**Comment by timbru31** [comment]
Just a random idea: could the Twitter feed/widget perhaps (still) use Flash?

**Comment by breautek** [comment]
> Just a random idea: could the Twitter feed/widget perhaps (still) use Flash?

I was thinking about this too... Perhaps if the tweet contains a video?

**Comment by NiklasMerz** [comment]
I just tested another browser (Firefox Linux, previous one was Firefox Windows) and there is a similar flash warning. Will investigate...

**Comment by NiklasMerz** [comment]
It should be [ZeroClipBoard](https://github.com/zeroclipboard/zeroclipboard) which is loading a `.swf` file. That should be the Flash script file

![grafik](https://user-images.githubusercontent.com/3585860/70657044-747a5f80-1c5b-11ea-8e5a-8c7dd3987df2.png)

Should be fairly easy to remove -> https://github.com/apache/cordova-docs/search?q=ZeroClipboard&unscoped_q=ZeroClipboard

Should I go ahead and create a PR?

**Comment by breautek** [comment]
Weird, I get a `ZeripClipboard.js` file, but I don't see a `ZeroClipboard.swf` file being requested (on chrome)

I see the same on firefox.

**Comment by NiklasMerz** [comment]
I just disabled the "Shockwave flash plugin" in Firefox on Linux and now the icon in the URL bar is gone. I cannot see the swf file too.

There is no point in keeping this library right? Flash is gone from modern modern browsers and EOL by Adobe in year as far as I know.

**Comment by breautek** [comment]
Not sure where this library is actually used, but I think generally speaking it can probably be refactored out based and use a pure js solution based on https://caniuse.com/#feat=clipboard

**Comment by brodybits** [comment]
I would also like to understand some historical context to understand *why* and what may be broken before removing things like this.

Starting from this line: https://github.com/apache/cordova-docs/blob/master/www/static/plugins/app.js#L29

I took a look through the history and discovered that this ZeroClipboard thing was introduced in PR #395.

Unfortunately PR #395 copied a bunch of files from some branch that I do not see any record of so far, at least. Bad for attribution of contributions and bad for understanding historical context of things.

**Comment by NiklasMerz** [comment]
I just did some searches and it looks like it is just used for the "copy" buttons next to the CLI commands on this page: https://cordova.apache.org/#getstarted

**Comment by NiklasMerz** [comment]
I think I may got removing ZeroClipBoard right. It works locally for me in Firefox and Chromium on Linux.

**Comment by dblotsky** [comment]
This was 100% for the “copy” buttons. I don’t recall now why JS-only wasn’t enough. Please validate on at least Ubuntu, macOS, and Windows on some modern set of browsers.

**Comment by NiklasMerz** [comment]
If this was done in 2015, those were different times :-). Maybe Internet Explorer? I dont't know much about the clipboard API, but I think it's time to get rid of flash now since most browser won't support it anyway.

I will test this on Windows and macOS at work soon. My test right now was done on Linux Mint (Ubuntu based).
