### ISSUE TITLE
Import history of Cordova website artifacts

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#1033]
Many, many, many files were added in PR #395 to merge an old cordova-website repository with this one, with zero history of the files that were added. This made it especially hard to understand the history behind the ZeroClipboard library that we discovered in issue #1031 and removed in PR #1032.

I was able to get *some* history of cordova-website from svn: https://github.com/apache/cordova-docs/blob/master/doc/deploying-the-website.md#manual-deployment

I don't know if svn should be considered the original source of the history or not.

/cc @dblotsky

**Comment by dblotsky** [comment]
I totally forgot about SVN. Yes, that is the history you’re looking for. It is where the website was before merging it into cordova-docs.

**Comment by brodybits** [comment]
Thanks @dblotsky for confirming.

Here is what I did to look through the history of cordova-website, starting from the beginning:

```sh
svn checkout https://svn.apache.org/repos/asf/cordova/site cordova-website
cd cordova-website
svn log -r 1:HEAD -v | more
```

I think we should try to import this history into git.

**Comment by dblotsky** [comment]
Is the history import worth the effort? I would pit it against the effort of finding answers without history.

IMO there are few enough files in this repo that just spelunking through them can give you answers without the SVN history.

**Comment by dblotsky** [comment]
Is the history import worth the effort? I would pit it against the effort of finding answers without history.

IMO there are few enough files in this repo that just spelunking through them can give you answers without the SVN history.

**Comment by brodybits** [comment]
I think the most important reason for preserving the history is to help people understand the context of things in the future. The prime example I gave was in removing the obsolete ZeroClipBoard library in PR #1032. We can see in PR #1032 that it broke something else in #1047. I think it is also good practice to preserve traceable authorship of our code from an IPR perspective.

I am fine to just keep that old history in svn for now, at least. You should see that I just added a note to PR #395 where the files were imported.

**Comment by erisu** [comment]
Closing out this ticket.

While I understand the importance of preserving history, I personally have not found the need to access the SVN history in the past. 

I believe it is unnecessary to migrate the history. It is still retrievable in SVN if someone dos need it.
