### ISSUE TITLE
Automatic doc build is broken (Travis CI)

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#1035]
# Bug Report

### What is expected to happen?

UPDATED: Automatic doc build should be done whenever we add a release note or update any other part of the documentation.

Travis CI build should just keep working whenever we merge PRs such as #1032.

### What does actually happen?

Travis CI build stopped working right after I merged PR #1032.

_Automatic doc builds from release notes and other updates is broken._

It looks to me like there is an issue with svn.

I am not an Apache website svn build expert. I really hope we can get the right expertise to look at this one.

### Command or Code

see .travis.yml

### Environment, Platform, Device

see .travis.yml

### Version information

N/A

## Checklist

- [x] I searched for existing GitHub issues
- ~~I updated all Cordova tooling to most recent version~~
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Ping @janpio - I remember there were some issues with docs in the past related to SVN and credentials.

**Comment by timbru31** [comment]
CI failure notice:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by janpio** [comment]
The SVN stuff is using my credentials, possible that they got blocked. Do not have a setup to confirm, so you might just want to replace with yours. (There is no real other solution possible as they this is pushed onto SVN is not supported by ASF Infra)

**Comment by brodybits** [comment]
I raised https://issues.apache.org/jira/browse/INFRA-19575 to get some help from INFRA.

**Comment by janpio** [comment]
This has been raised before (a fews times actually), and there are multiple other solutions for websites in ASF - non which match the setup Cordova is currently using.

**Comment by brodybits** [comment]
Thanks @janpio. As I said in INFRA-19575, I would really favor that we find a way to work with Apache INFRA, rather than using individual dev credentials from myself or anyone else.

**Comment by brodybits** [comment]
This issue affects automatic build of release notes such as cordova-node-xcode@2.1.0 (PR #1037). I just updated the title and description, pinning now.

**Comment by NiklasMerz** [comment]
Is the automatic build working again? I was about to do a manual deploy but master was already deployed with a SVN commit by janpio.

**Comment by erisu** [comment]
Closing ticket as the automatic build is working.
