### ISSUE TITLE
App is not working on android version above than 8

### ISSUE THREAD

**Issue by Ravi889** [apache/cordova-docs#1040]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Please edit the issue and fill out the form.

**Comment by breautek** [comment]
Closing due to lack of response.
