### ISSUE TITLE
ionic support android 10 width cordova

### ISSUE THREAD

**Issue by GravesDXD** [apache/cordova-docs#1041]
I want to know how the ionic3 project supports Android 10 width cordova. I have downloaded the latest SDK29,and changed the config ToolsVersion to 29. but I found Android 10 mobile crash and is not compatible after downloaded and installed. but other Android is ok, like Android 9. how to fix it. thanks a lot

**Comment by jcesarmobile** [comment]
Closing as this is not an issue, it’s a question.

Cordova-android 9 will target SDK 29, some plugins will need to be updated to properly support it.
