### ISSUE TITLE
Plugin search doesn’t work

### ISSUE THREAD

**Issue by ciossi** [apache/cordova-docs#1047]
# Bug Report

The plugin search at the url https://cordova.apache.org/plugins/ doesn’t work.

## Problem

It keeps loading 

### What is expected to happen?

The list of all Cordova plugin

### What does actually happen?

Nothing

**Comment by erisu** [comment]
The plugin loading issue might be triggered by failing JS.

This PR, https://github.com/apache/cordova-docs/pull/1032, which removed the `ZeroClipBoard` also removed the `setClipboardText` method. This method is still referenced/used `plugins.js`. 

I believe that when this error is fixed, it is possible that the remaining script will complete its execution and loads the plugin list.

**Comment by NiklasMerz** [comment]
I fixed the `ZeroClipBoard` errors now. But there is still another problem:

I will look into this soon, but it works for me:
![grafik](https://user-images.githubusercontent.com/3585860/72552705-c2f0ce80-3897-11ea-9901-c26ad244fac7.png)

**Comment by ciossi** [comment]
The search for plugin list on the website https://cordova.apache.org/plugins/ doesn't still work...

![cordova plugin list error](https://user-images.githubusercontent.com/11943849/72607802-9b464880-3921-11ea-98c8-07c58e97bd18.PNG)

**Comment by erisu** [comment]
Please wait until the PR is merged and deployed.

**Comment by NiklasMerz** [comment]
I can check the other errors soon.

**Comment by NiklasMerz** [comment]
Two fixes have been merged and deployed. The issue should be solved now. Thank you all.

**Comment by alijamal14** [comment]
Its not working again
![image](https://user-images.githubusercontent.com/2056312/142582741-cf5b83e8-de8a-4687-a9f0-59a578dd3142.png)

**Comment by breautek** [comment]
This issue describes a much older issue.

https://github.com/apache/cordova-docs/issues/1128 is a newer ticket tracking the current issue.
