### ISSUE TITLE
feature tag seems to be missing in plugin reference

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#1051]
The feature and param tags are part of the config-file in plugin.xml but seems to be not documented in https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html

While I do see examples in plugin documentation for Android and iOS, I would expect these tags to be documented in the reference.

**Comment by erisu** [comment]
It is documented in the **`config.xml`** page.

Even though plugins usually define this in the `plugin.xml` file, it is injected into the platform-level **`config.xml`** by using the `config-file` block.
It is still considered as a **`config.xml`** element. It just not expected to be defined in the project's top-level **`config.xml`** file.

Closing ticket as no planned.
