### ISSUE TITLE
Add "team" page for community members

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-docs#1060]
# Feature Request

## Motivation Behind Feature
We could add page to the website where community members could add their bio and/or description how they work on Cordova. This creates visbility around the commiters for "outside" Cordova users who want know who works on project. 

Commiters could add their expertise around Cordova sub-projects for others to find the right person to ask questions or ask for reviews.

## Feature Description
I imagine something like this http://plc4x.apache.org/developers/team.html

An optinal images, name, link and description. I think every commiter/community member should add their info themselve. So we create the page and everbody who wants to add some info can create a PR.

**Comment by brodybits** [comment]
Thanks @NiklasMerz, is there anything the rest of us can do to help make this happen?

I really hope to find a way to further improve the synergy between my contributions to Apache Cordova and my work as a freelancer.

**Comment by NiklasMerz** [comment]
If you or someone else is more familiar with cordova-docs or has ideas just go fo it and create a PR.

I will have a look in the next few days. Looks like some of the website is written in React which is not my strongest framework.
