### ISSUE TITLE
Remove twitter feed from blog site

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-docs#1069]
# Feature Request

## Motivation Behind Feature

The Cordova PMC is no longer active on Twitter. the feed should be removed to avoid confusions with really old posts.

## Feature Description

Remove feed from blog page: https://cordova.apache.org/blog/
Remove other Twitter references?

**Comment by timbru31** [comment]
Heretical questions:
a) should we revive the account?
b) who owns the account currently?

**Comment by NiklasMerz** [comment]
I think Option a would be the best if possible.

b) We as PMC have credentials for this account the seem to have stopped working because of some Twitter passwort reset or something like that.

Should we bring the this to the mailing list?

**Comment by timbru31** [comment]
IMHO we should use all possible channels to make aware that Cordova is still active and maintained, so yes, I'd vote for a resurrection (via the mailing list).

**Comment by breautek** [comment]
Since we are using twitter again, I assume this ticket can be closed?

**Comment by timbru31** [comment]
Yes, I’ll agree with that. Closing.
