### ISSUE TITLE
Doc: Android Support Repository 

### ISSUE THREAD

**Issue by markwaldin** [apache/cordova-docs#1073]
# Bug Report

Support Repository no longer available in Android SDK

Install instructions say the the Android Support Repository must be installed in the Android SDK  and I expected to find it in the list

It is not in the install list because it is no longer supported and has been replaced by Maven 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by brodybits** [comment]
I think this should be part of #1057.

**Comment by mosabab** [comment]
I created a pull request to update the Documents regarding this.

https://github.com/apache/cordova-docs/pull/1094
