### ISSUE TITLE
Documentation suggests use of poor security practices - consider reviewing if appropriate

### ISSUE THREAD

**Issue by stuartw1** [apache/cordova-docs#1080]
# Bug Report

## Problem

I read the following documentation page https://cordova.apache.org/docs/en/latest/guide/appdev/security/ which appears to contain questionable security advice. 

The Cordova documentation suggests use of cleartext HTTP on a trusted network. This will provide no encryption of data or authentication of servers. If a malicious third party gains access to the network or manages to compromise a machine on it, connections using cleartext HTTP will be vulnerable to sniffing / modification / service spoofing by the third party (or any malware they have managed to place). 

Self signed certificates are discouraged in the documentation, though would probably be better than nothing in most cases - they offer host authentication and connection encryption if the fingerprint was manually verified (though most users will just accept them or may become conditioned to accept them which is bad). A man in the middle attack requires a user action to ignore security protections. This is not the case with HTTP. A user will be safe if they follow the instructions in their browser and verify the certificate when they accept it and most devices will store the exception for future use and warn if a certificate changes. A man in the middle attack requires active interaction with the network rather than passive sniffing. Sensitive cleartext data may also be recorded in logging and monitoring systems, though use of self-signed certificates would avoid this.

The use of an internal corporate certificate authority trusted by devices used within an organisation is not suggested. This is recommended for applications used on internal networks and the connections will be protected by HTTPS (hosts cannot be spoofed by third parties and the connections cannot be intercepted or have data modified). This is probably the best option for internal use inside an organisation when a trusted third party SSL certificate has not or cannot be obtained.

The use of free trusted third party certificate authorities (like LetsEncrypt or an alternative) is not suggested. This is recommended for servers which are publicly facing and allows the application to benefit from HTTPS without purchasing an SSL certificate or using a 'self-signed' one.

### What is expected to happen?

The documentation should provide useful security advice matching current best practices.
Consider linking to the OWASP mobile security pages for additional reading

### What does actually happen?

The documentation suggests using cleartext HTTP (as anything other than a last resort) and does not adequately explain the drawbacks. This is poor security practice, even on a trusted internal network. There are easy and secure alternatives available

### Environment, Platform, Device

Cordova docs https://cordova.apache.org/docs/en/latest/guide/appdev/security/

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version (latest version of live website on 13th May 2020)
- [x] I included all the necessary information above

Edit: minor style edits

**Comment by breautek** [comment]
I definitely think this could be cleaned up. I'd support a PR that removes text recommending cleartext HTTP and to provide up-to-date recommendations instead.

**Comment by breautek** [comment]
Hi @stuartw1 I'd welcome your review and feedback on #1109
