### ISSUE TITLE
Quasar is not listed on the frontpage?

### ISSUE THREAD

**Issue by francoism90** [apache/cordova-docs#1134]
# Feature Request

## Motivation Behind Feature
[Quasar](https://quasar.dev/quasar-cli/developing-cordova-apps/introduction) provides out-of-the-box integration with Cordova. Why isn't this framework listed on the [Cordova homepage](https://cordova.apache.org/) in the tools section? I think they deserve a mention as it works really well under Cordova.

## Feature Description
A lot of great tools are listed already on the homepage, it would be great if Quasar could be added as well.

## Alternatives or Workarounds
Sorry if this isn't the correct place, I cannot seem to add a bugreport on the Cordova issue tracker.

Thanks. :)

**Comment by breautek** [comment]
Someone who represents Quasar (or at the very least has written permission to do so) can make a PR by modifying https://github.com/apache/cordova-docs/blob/master/www/_data/tools.yml in this repo.

**Comment by francoism90** [comment]
@breautek Thanks, I'll try to contact someone of the Quasar team and see if they are interested. :)

**Comment by webnoob** [comment]
@breautek Thanks for that. I've added the PR (you'll be able to see on my profile I belong to the Quasar organisation).
