### ISSUE TITLE
Update documentation to use more inclusive language

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1140]
Related to https://github.com/apache/cordova/issues/218

Offending pages:
- https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/index.html
- https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/index.html
- https://cordova.apache.org/docs/en/latest/guide/appdev/security/index.html

**Comment by timbru31** [comment]
I guess, we would need to come up with some sort of redirection?

**Comment by breautek** [comment]
> I guess, we would need to come up with some sort of redirection?

That would be ideal...

**Comment by breautek** [comment]
Completed by https://github.com/apache/cordova-docs/pull/1142
