### ISSUE TITLE
Where to download complete documenation for offline reading purpose?

### ISSUE THREAD

**Issue by maqeelqureshi** [apache/cordova-docs#1148]
How can I download to print complete documentation?

**Comment by timbru31** [comment]
Tough question! I don't think we support nor will we support some sort of offline/download use case. But if I were you, I would clone the git repo and follow the README how to generate the docs locally - then you can print all the HTML pages you want or write some little script to do that in a loop.

**Comment by timbru31** [comment]
One of our PMC members linked me to https://kapeli.com/dash - maybe that works in your case, too (if you are on macOS) or you can find alternatives for Windows.
