### ISSUE TITLE
Plugin search doesn’t work well and isn't updating from npm

### ISSUE THREAD

**Issue by nickredding** [apache/cordova-docs#1165]
# Bug Report

### What is expected to happen?
Typing in the text search box should progressively show matching plugins available on npm.

Plugins recently published on npm should be found.

### What does actually happen?
After a few characters, the text box keeps losing focus after every subsequent character (requiring the user to click inside the box to restore focus and continue typing)

A plugin published 9 days ago (cordova-plugin-apple-watch-link) is not found by the plugin search (it is found in npm search).

The package.json file for the plugin contains

"keywords": [
    "cordova",
    "apple",
    "watch",
    "watchkit",
    "message",
    "extension",
    "notification",
    "ecosystem:cordova",
    "cordova-ios"
  ]

which should be sufficient (according to the cordova docs) to surface the plugin in plugin search.

## Information

Using lates t Chrome browser on Windows.

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Closing as duplicate from https://github.com/apache/cordova-docs/issues/1128
