### ISSUE TITLE
document missing android preferences

### ISSUE THREAD

**Issue by erisu** [apache/cordova-docs#1169]
# Documentation Request

Add new `config.xml` preference `AndroidXAppCompatVersion` to document.

This preference is:

* Only for the `Android` patform
* Defaults set to `1.2.0` the current latest stable version of the `AppCompat` library.

Add a note that changing is at the users own risk.

**Comment by erisu** [comment]
Linked Feature PR: https://github.com/apache/cordova-android/pull/1208

**Comment by jcesarmobile** [comment]
This ones are missing too:

android-compileSdkVersion (null)
android-buildToolsVersion (32.0.0)
GradleVersion (7.4.2)
AndroidGradlePluginVersion (7.2.1)
AndroidXWebKitVersion (1.4.0)

I've updated the title to cover all
