### ISSUE TITLE
I think CordovaWebViewEngine now defaults to WK

### ISSUE THREAD

**Issue by byronigoe** [apache/cordova-docs#1221]
# Bug Report

## Problem

https://cordova.apache.org/docs/en/10.x/config_ref/ has listings for CordovaWebViewEngine and CordovaDefaultWebViewEngine, both of which say they default to CDVUIWebViewEngine. I don't think this is accurate any more, as I think CDVWebViewEngine is now the default (which I think uses WebKit). Also the examples at the bottom of that page for these two preferences should be updated.

### Version information

Cordova Docs 10.x

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Correct, `CDVWebViewEngine` is the new default as shown [here](https://github.com/apache/cordova-ios/blob/67b0bb2cfceb3f04fcd25a09222e86404805c594/CordovaLib/Classes/Public/CDVViewController.m#L451).

PR is welcome.

**Comment by DAnn2012** [comment]
Fixed in https://cordova.apache.org/docs/en/dev/config_ref/index.html#preference by #1112 and in https://cordova.apache.org/docs/en/11.x/config_ref/index.html#preference by #1226
