### ISSUE TITLE
The "Platform Pinning" page is outdated

### ISSUE THREAD

**Issue by DAnn2012** [apache/cordova-docs#1231]
The "Platform Pinning" page of versions 10.x, 11.x and Dev is obsolete because it is that of version 9.x

https://cordova.apache.org/docs/en/10.x/platform_pinning/index.html
https://cordova.apache.org/docs/en/11.x/platform_pinning/index.html
https://cordova.apache.org/docs/en/dev/platform_pinning/index.html

![Platform Pinning](https://user-images.githubusercontent.com/1197819/153643108-d20c81df-8be6-4580-9c78-994fcac518bf.png)

Thanks.

**Comment by breautek** [comment]
This page is explaining the platform pinning behaviour that the CLI does, so I think we can probably just remove `9.x` and leave it open ended. We could also probably remove `windows` and `osx` in the example output as they are deprecated platforms.

What are your thoughts on this?
