### ISSUE TITLE
Cordova plugins cant fetch

### ISSUE THREAD

**Issue by t1a2l** [apache/cordova-docs#1247]
Didn't know where to report, the plugin search on the cordova website is down, i cannot download or add plugins to my project. 
(using npmsearch.com which is not working).

**Comment by breautek** [comment]
For `npmsearch` / plugins search on the website, there is already an issue open at https://github.com/apache/cordova-docs/issues/1128

If you want to search for plugins, the current workaround search [npmjs.org](https://www.npmjs.com/search?q=cordova%3A)

If you actually have an issue using `cordova plugin install ...` to install plugins, then I'd suggest creating an issue with the issue form filled out inside our [cordova-fetch](https://github.com/apache/cordova-fetch) repository. Alternatively, you can ask our [Slack](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) community for support.

Closing as duplicate.

**Comment by t1a2l** [comment]
@breautek Can you give me a link to the Slack? I need a new invite.
