### ISSUE TITLE
Document new android preferences

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1255]
# Feature Request

## Motivation Behind Feature

To document new preferences that was added in cordova-android.
Brought to our attention by: https://github.com/apache/cordova-android/pull/1410#issuecomment-1193351277

Most of the new preferences was introduced in https://github.com/apache/cordova-android/pull/1212

The current list of preferences for android can be found at (omitting the preferences that is already documented): https://github.com/apache/cordova-android/blob/60e3803c67734087b7a6ff8ee8bd3a659cb050f8/lib/prepare.js#L99-L111

```javascript
        { xmlKey: 'android-compileSdkVersion', gradleKey: 'COMPILE_SDK_VERSION', type: Number },
        { xmlKey: 'android-buildToolsVersion', gradleKey: 'BUILD_TOOLS_VERSION', type: String },
        { xmlKey: 'GradleVersion', gradleKey: 'GRADLE_VERSION', type: String },
        { xmlKey: 'AndroidGradlePluginVersion', gradleKey: 'AGP_VERSION', type: String },
        { xmlKey: 'AndroidXAppCompatVersion', gradleKey: 'ANDROIDX_APP_COMPAT_VERSION', type: String },
        { xmlKey: 'AndroidXWebKitVersion', gradleKey: 'ANDROIDX_WEBKIT_VERSION', type: String },
        { xmlKey: 'GradlePluginGoogleServicesVersion', gradleKey: 'GRADLE_PLUGIN_GOOGLE_SERVICES_VERSION', type: String },
        { xmlKey: 'GradlePluginGoogleServicesEnabled', gradleKey: 'IS_GRADLE_PLUGIN_GOOGLE_SERVICES_ENABLED', type: Boolean },
```

I'll list some suggested brief descriptions, which is not set in stone, and definitely not meant to be copied and pasted. They are just general highlights of what the preference is used for. Reviews can be done in any given PRs.

### android-compileSdkVersion

Defaults to `android-targetSdkVersion`. Sets the compile sdk version setting. Should find android doc link.

### android-buildToolsVersion

Defaults are cordova-android version dependent. Expects a full version string `eg. "32.0.0"`. Changing this may also requires changing the `PATH` environment variable to find the proper build tools.

This preference is primarily for cordova development, for testing upcoming versions of the Android SDK. Changing this has a high risk of breaking builds as newer build tools frequently introduce breaking changes.

### GradleVersion

Sets the gradle wrapper version to use. 

This preference is primarily for cordova development, for testing upcoming versions of the Android SDK. Changing this has a high risk of breaking builds as newer build tools frequently introduce breaking changes.

### AndroidGradlePluginVersion

Sets the Android Gradle Plugin version to use. 

This preference is primarily for cordova development, for testing upcoming versions of the Android SDK. Changing this has a high risk of breaking builds as newer build tools frequently introduce breaking changes.

### AndroidXAppCompatVersion

Someone more knowledgeable will have to fill in the description for me. (Maybe brief description of what the AndroidX App Compat is used for?)

### AndroidXWebKitVersion

Someone more knowledgeable will have to fill in the description for me. (Maybe brief description of what the AndroidX Webkit dependency is for?)

### GradlePluginGoogleServicesVersion

Overrides the google services library version.

### GradlePluginGoogleServicesEnabled

Enables Google Services. (I think google API keys are required?)

**Comment by erisu** [comment]
#1169
