### ISSUE TITLE
Missing anchor for edit-config and config-file for the plugin.xml doc

### ISSUE THREAD

**Issue by Heshyo** [apache/cordova-docs#1281]
# Bug Report
https://cordova.apache.org/docs/en/11.x/config_ref/index.html uses the links https://cordova.apache.org/docs/en/11.x/plugin_ref/spec.html#edit-config and https://cordova.apache.org/docs/en/11.x/plugin_ref/spec.html#config-file for `<edit-config> docs` and `<config-file> docs` respectively.

## Problem
The anchors `spec.html#edit-config` and `spec.html#config-file` do not exist.

### What is expected to happen?
The page should scroll down to the `edit-config` and `config-file` sections.

### What does actually happen?
The page does not scroll to the expected sections.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Both links are working properly for me on Chrome.

Is there a specific browser that this doesn't work?

**Comment by Heshyo** [comment]
I was browsing the site without javascript. With javascript on, indeed the links redirect to the correct parts.
