### ISSUE TITLE
Document: CORDOVA_JAVA_HOME environment variable

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1292]
As pointed out by https://github.com/apache/cordova-android/pull/1229#issuecomment-1493993119

The `CORDOVA_JAVA_HOME` is not documented as an option. `CORDOVA_JAVA_HOME` will take precedence over `JAVA_HOME` if set.

The feature was added in v10 of cordova-android.

**Comment by breautek** [comment]
> This is other issue however, as for sure JAVA_HOME works not only on Windows, but macOS as well.
>
> I bet specific OS should be omitted.

For sure... I didn't change what was already, there I just appended. However this is definitely true and I think this is a good opportunity to address that. Thank you for pointing that out.

**Comment by paulwwisl** [comment]
It is live at https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#java-development-kit-jdk

And it feels like it should be moved to section https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#setting-environment-variables

**Comment by breautek** [comment]
> It is live at https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#java-development-kit-jdk
> 
> And it feels like it should be moved to section https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#setting-environment-variables

I would... also agree with that. A PR is welcome to move it.
