### ISSUE TITLE
Android SDK Install Instructions - Explicitly declare which packages are needed

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1296]
As pointed out by https://github.com/apache/cordova-android/issues/1585#issuecomment-1506543536

The installation docs for the Android SDK enviornment, it isn't clear which SDK packages are required or necessary.

For example, it references adding `cmdline-tools/latest/bin` to the PATH, but doesn't explain how to get the `cmdline-tools` package in the first place.

[Adding SDK Packages](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#adding-sdk-packages) should be revised to ensure that it pinpoints all packages required.

[Android SDK Tools](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#android-sdk-tools) section should also be revised because I don't believe it's actually relevant to modern environments anymore. ~(Do we really need obsolete packages? I believe this may refer to the old Java 8 tooling)~ Confirmed, this installs the `/tools` directory, which is not compatible with Java 11 runtimes, `cmdline-tools` is the replacement.

The following packages at minimum should be installed:

#### SDK Platforms
- API level (dependent on cordova-android version, maybe provide a chart by cordova-android version)

#### SDK Tools
- Android SDK Build-Tools` (dependent on cordova-android version)
- `Android SDK Command-line Tools (Latest)`
- - Optional, but will provide Cordova the ability to use `avdmanager` to find installed emulators.
- `Android Emulator`
- - Optional, but definitely useful.
- `Android SDK Platform-Tools`
- - Contains the `adb` tool for debugging physical devices.

Lastly, I also thing we should note that if `Android SDK Tools (Obsolete)` is installed, it can be safely uninstalled. Additionally we can also note that above packages is what used, may be used by Cordova or useful in Android Development in general. Third-party plugins may have additional requirements, such as `Google Play Services`

**Comment by aaarichter** [comment]
one more point that is missing was covered in this solution: https://www.freakyjolly.com/resolved-no-usable-android-build-tools-found-highest-30-x-installed-version-is-30-0-2-minimum-version-required-is-30-0-3/

the latest Android Studio ships with the android build tools 34.0.0-rc3, but the latest cordova-android only works with 32.0.0
