### ISSUE TITLE
DOAP file has an error.

### ISSUE THREAD

**Issue by Claudenw** [apache/cordova-docs#1298]
# Bug Report

## Problem
The DOAP file [1] as listed in [2] has the error:

 [line: 87, col: 84] {W002} <mailto:java-dev@axis.apache.org?subject=[Axis2]> Code: 0/ILLEGAL_CHARACTER in QUERY: The character violates the grammar rules for URIs/IRIs.

[1] http://svn.apache.org/repos/asf/axis/axis2/java/core/trunk/etc/doap_Axis2.rdf
[2] https://svn.apache.org/repos/asf/comdev/projects.apache.org/trunk/data/projects.xml

### What is expected to happen?

Correct parsing of file.

### What does actually happen?

Parsing fails with the error above.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Correct me if I'm wrong but... that seems to be related to the Apache Axis... not Apache Cordova... via https://github.com/apache/axis-axis2-java-core/blob/master/etc/doap_Axis2.rdf

May want to reach out to Apache Axis2 via their [Issue Tracking](https://axis.apache.org/axis2/java/core/issue-tracking.html#).

**Comment by breautek** [comment]
Closing as stale/no response.

The issue appears to be related to other Apache projects, but not Apache Cordova.
