### ISSUE TITLE
Add Cordova Android 12 docs on https://cordova.apache.org/

### ISSUE THREAD

**Issue by pinguluk** [apache/cordova-docs#1327]
# Feature Request
Update the docs from https://cordova.apache.org/ to include Cordova Android 12

## Motivation Behind Feature

Latest Android Cordova on the main site is 11, even if 12 was released a few months ago.
In the [repository ](https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/platforms/android/index.md)I see that Android 12 docs has been added, but the site.

## Feature Description

---

## Alternatives or Workarounds

---

**Comment by erisu** [comment]
Already been added: https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html#android-api-level-support

Just that the docs were not sliced for Cordova CLI 12.
