### ISSUE TITLE
DOC: documentation not searchable?

### ISSUE THREAD

**Issue by jablka** [apache/cordova-docs#1338]
this is probably a bug: the official documentation website is not searchable?

Try typing anything in the search bar [https://cordova.apache.org/docs/en/latest/](https://cordova.apache.org/docs/en/latest/)

I get no search results, as if the button does not work.

**Comment by breautek** [comment]
Duplicate of https://github.com/apache/cordova-docs/issues/1294#issuecomment-1750561330
