### ISSUE TITLE
GradlePluginGoogleServicesEnabled duplicated

### ISSUE THREAD

**Issue by zhictory** [apache/cordova-docs#1362]
# Bug Report

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by zhictory** [comment]
![image](https://github.com/user-attachments/assets/caa45fde-9bd8-4e67-bf97-a4c72a95aef1)

**Comment by breautek** [comment]
ye that second one I think should be `GradlePluginGoogleServicesVersion` but I'd have to go look up the key to confirm.
