### ISSUE TITLE
Splashscreen ShowSplashScreenSpinner is documented as supported on iOS

### ISSUE THREAD

**Issue by breautek** [apache/cordova-docs#1381]
Which doesn't appear to be the case anymore:

https://github.com/apache/cordova-ios/issues/1503#issuecomment-2470826381

> The ShowSplashScreenSpinner preference isn't supported on iOS anymore after the move to Storyboard-based splashscreens. (It also, for what it's worth, doesn't appear to be supported on Android anymore with the newer splashscreens there.)

The documentation doesn't state that it's supported on Android either and I'm pretty confident that the android splashscreen system doesn't have the capability, so I think the entire section can probably be removed.

**Comment by dpogue** [comment]
I believe this was cleaned up as part of https://github.com/apache/cordova-docs/pull/1348 but there does still seem to be a dead link in the TOC for the Splashscreen page.

**Comment by breautek** [comment]
Yah looks like the case, I forgot to check the `dev` version of the docs earlier.

So I think we just fix the TOC then.
