### ISSUE TITLE
Retired Tools should be removed from landing page

### ISSUE THREAD

**Issue by Menardi** [apache/cordova-docs#819]
Some of the tools on the home page have been retired, and should be removed from the landing page.

- Telerik - Retired on May 10, 2018 ([Retirement announcement](https://www.telerik.com/platform-next-level))
- GapDebug - Retired in 2016 (Notice on [homepage](https://www.genuitec.com/products/gapdebug-end-of-life-notice/))

Additionally, the link for Visual Studio is broken. I will address these in a PR shortly.

**Comment by shazron** [comment]
Merged #820
