### ISSUE TITLE
List sentry.io

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#829]
**Issue Type**
- [ ] Bug
- [x] Feature Request

**Priority**
- [ ] Minor 
- [x] Major 
- [ ] Critical 
- [ ] Blocker 

**Environment**
* OS: all
* Browser: all

**Description**

The sentry.io tool provides automatic detection and tracking of internal application errors that may happen in the field. I had a client waste quite a bit of time building this kind of system into her app before finding this tool.

Partial overlap with instabug (GH-827).

**Comment by breautek** [comment]
PR welcome: https://github.com/apache/cordova-docs/blob/master/www/_data/tools.yml

**Comment by breautek** [comment]
Closing as stale
