### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by DevinCarpenter** [apache/cordova-docs#831]
**Issue Type**
[ x ] Bug
[ ] Feature Request

**Priority**
[ x ] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* ALL OS's

**Description**

Links for AppVeyor and TravisCI on the website page for [cordova-plugin-globalization](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-globalization/) show build passing and are actually pointing to the page for cordova-plugin-geolocation, when it should be to it's own plugin page.

To Reproduce: Click on the AppVeyor or TravisCI link on [cordova-plugin-globalization](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-globalization/) page.

**Comment by janpio** [comment]
The plugin references come from the plugin's Github repository README. You should be able to find the link there, replace it and send a PR with the fix.

**Comment by janpio** [comment]
I fixed the links in the `cordova-plugin-globalization` README, so this should fix itself in the docs with the next deploy.
