### ISSUE TITLE
Missing documentation for OSX icons

### ISSUE THREAD

**Issue by jazbek** [apache/cordova-docs#833]
**Issue Type**
[ x] Bug
[ ] Feature Request

**Priority**
[ x ] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: OS X

**Description**
The documentation page that describes how to set up icons does not include any information on the OSX platform. I am marking this issue as Minor, but only because I googled extensively and could not find any answers, which leads me to believe that it's not affecting many people. However, for those of us building an OS X app with cordova, it's pretty important! :)

**Comment by janpio** [comment]
Hey @jazbek, did you find out any information in the meantime that could be added to the docs?

**Comment by jazbek** [comment]
@janpio sorry for the late reply -- I ended up finding a youtube video (https://www.youtube.com/watch?v=EtFJGJtm5Tc) that explained how to do it directly in Xcode. I vaguely recall that the video had slightly incorrect information and I ended up futzing with it for a while until it worked, and I can't say that I documented all the steps I took.

So, long story short, no, I didn't find any cordova-related info that could be added to the docs. Sorry!

**Comment by janpio** [comment]
Well, maybe some day someone will go through the steps again and update the docs. Until then I will close this here. Thanks anyway!

**Comment by janpio** [comment]
Actually, why not just leave it open to track that this is missing.

**Comment by erisu** [comment]
Closing out this ticket as the Cordova-OSX platform has been deprecated and will be removed in the upcoming doc release version.

It is unlikely that the older documentation will be updated.
