### ISSUE TITLE
About Chinese Simplified translation

### ISSUE THREAD

**Issue by Ray-Eldath** [apache/cordova-docs#841]
**Issue Type**
[ ] Bug
[X] Feature Request

**Priority**
[ ] Minor 
[X] Major 
[ ] Critical 
[ ] Blocker 

**Description**

The Simplified Chinese [简体中文] translation of cordova-doc is **totally incorrect**! Actually, it's *just a copy* of  Traditional Chinese translation.
I think you can use Traditional Chinese - Simplified Chinese converter which is being used by Wikipedia. See: [Automatic conversion between simplified and traditional Chinese](https://meta.wikimedia.org/wiki/Automatic_conversion_between_simplified_and_traditional_Chinese) and [MediaWiki / LanguageZh.php](https://github.com/wikimedia/mediawiki/blob/05c72943a7bb06f618c7bd6f01cbbc2ce0665178/languages/classes/LanguageZh.php)
But I think there is high-quality Simplified Chinese translation already, maybe you can use theirs. See: [Cordova中文网](http://cordova.axuer.com)

**Comment by jcesarmobile** [comment]
Thanks for the issue, but translations are going to be removed, so this won’t be fixed
