### ISSUE TITLE
Cordova Docs Layout is Messed Up

### ISSUE THREAD

**Issue by GimpMaster** [apache/cordova-docs#845]
**Issue Type**
[X ] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[ ] Major 
[ X] Critical 
[ ] Blocker 

**Environment**
* OS: Mac
* Browser: Chrome

**Description**

Recently the Cordova Plugin docs have a CSS layout issue. See screenshot for an example and a URL of the corresponding issue.

![screen shot 2018-07-13 at 3 34 44 pm](https://user-images.githubusercontent.com/7818200/42715122-b60dfb4a-86b2-11e8-8378-90ffb0e2bf34.png)

**Comment by dpogue** [comment]
hmm, we did deploy an update to the site recently to adjust some styling for better readability, but none of my coworkers see this problem in Chrome. If you've visited this page in the past week and then visited it after we deployed the update, it's possible that you're seeing a cached version of the stylesheet. Could you try a force refresh or clearing your browser cache?

For reference, this is what I see at that URL:
<img width="776" alt="screen shot 2018-07-13 at 14 47 32" src="https://user-images.githubusercontent.com/241708/42715392-b16501da-86ab-11e8-894c-5d8b4b0b5ce4.png">

**Comment by GimpMaster** [comment]
That was it!  Thank you.

**Comment by raphinesse** [comment]
Ouch, we should have a cache busting mechanism (like appending resource hashes to resource names) in our build. This probably concerns more than only one user.

I guess any react app created from a recent boilerplate should have something like this.

**Comment by janpio** [comment]
No React in Cordova docs for sure ;)

**Comment by raphinesse** [comment]
@janpio I'm confused. I'm almost certain I edited a `*.jsx` file in #848 :confused:

**Comment by janpio** [comment]
... which is the plugins subpage/project, which is also part of the `cordova-docs` repo, but not the Cordova documentation pages. (`cordova-docs` could/should be called `cordova-website`, but isn't.)

**Comment by erisu** [comment]
@janpio I think 3 years ago someone tried to rename `cordova-docs` to `cordova-website` but the repo name was not updated. You can see in `package.json` that it was changed then from `cordova-docs` to `cordova-website`.

**Comment by janpio** [comment]
> I stand by my statement that any part of the docs should have cache busting.

100% agreement here.

> I think 3 years ago someone tried to rename cordova-docs to cordova-website but the repo name was not updated. You can see in package.json that it was changed then from cordova-docs to cordova-website.

It's very possible the repo was named that way some time ago... many strange things happened here already ;) Do you think it is worth to rename it now @erisu?
