### ISSUE TITLE
"Tooling" page

### ISSUE THREAD

**Issue by janpio** [apache/cordova-docs#847]
Currently the start page lists a number of tools that work with Cordova. But space is limited, and it should be in our interest to be able to list as many tools and services as possible.

I suggest a new "Tooling" (or "Tools to use with your apps" or similar) in the docs itself in list format, maybe grouped by category, where those can be listed with a short description. All companies offering such tools should be interested in being listed there, but also libraries and other stuff could be added.

The page could be linked below the "most important" tools listed on the website itself.

(Related: #829)

To define:

- [ ]  Page title
- [ ]  Page URL
- [ ]  Location in docs navigation
- [ ] Categories
- [ ] Start content

**Comment by janpio** [comment]
related to #869

**Comment by breautek** [comment]
Closing as we now have a dedicated "Third-party Tooling" page.
