### ISSUE TITLE
Update Contributor guidelines for GitHub Issues activation

### ISSUE THREAD

**Issue by janpio** [apache/cordova-docs#861]
Collection of stuff that has to be changed when switching over to Github issues:

https://cordova.apache.org/contribute/
- Change "View All Issues" and replace Issue Search

https://cordova.apache.org/contribute/issues.html
- Remove references to JIRA
- Remove "Issue Priority"
- Add link to new page that will be created via #860

https://cordova.apache.org/contribute/contribute_guidelines.html
- Remove references to JIRA
- Simplify "Making Pull requests" and "Git Commit Messages"

Anything missing?

**Comment by brodybits** [comment]
I will need some more time to look through Cordova to verify that nothing is missing.

**Comment by janpio** [comment]
I broadened the scope of this by creating https://github.com/apache/cordova-contribute as a central repository that contains all contributor documentation. Depending on how this turns out, we might want to pull in the files from that repo to the public website - or just link it from the appropriate places.

**Comment by brodybits** [comment]
> https://github.com/apache/cordova-contribute

Does not seem to have issues enabled

**Comment by janpio** [comment]
As usual with new Github repositories by Apache. But that's ok for now, I will take care of it as soon as I officially announced it to the dev list and "started" it with some PRs for content.
