### ISSUE TITLE
ios-deploy questions

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#866]
**Issue Type**
[ ] ~~Bug~~
[ ] ~~Feature Request~~
[ ] Question

**Priority**
[ ] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: macOS
* Browser: ??

**Description**

From <https://github.com/apache/cordova-ios/pull/377#discussion_r206744539> I realized that a couple things are not so clear:
1. Why not make ios-deploy a dependency of cordova-ios that would then be automatically installed?
2. Is there a risk of mismatch between a users installed ios-deploy version and a users Cordova version? Should this be documented, if so?

I think the answer to 1 is that ios-deploy *sometimes* needs to be installed with more system privs. I am not 100% sure of this, would love some confirmation from an expert. And I think this is not really a problem most of the time.

I think the answer to 2 is "not yet".

**Comment by janpio** [comment]
This is not a question about `cordova-docs` but `cordova-ios`. 
Please create the issue in a more approriate place or ask in Slask or the mailing list.

**Comment by janpio** [comment]
If your question was "Should this be documented in another way?" then it would be valid here, but as it is "Should this be different?", this is not an issue with `cordova-docs`.
