### ISSUE TITLE
How to call javascript method from my plugin file (iOS-platform)

### ISSUE THREAD

**Issue by MZabih** [apache/cordova-docs#868]
I created a `cordova-plugin` for my ionic-1 app (iOS Platform). I want to call method that has been created in `js` file of my ionic project, from native iOs class in objective-c file of my cordova-plugin.

**Comment by janpio** [comment]
Unfortunately this repository is only for issues about `cordova-docs`, the website and documentation itself. Your question is more fitting for the Cordova Slack (slack.cordova.io), JIRA issues for `cordova-ios` (issues.cordova.io) or even the Ionic forum at forum.ionicframework.com. Thank you.
