### ISSUE TITLE
Search in docs top bar not working

### ISSUE THREAD

**Issue by Menardi** [apache/cordova-docs#872]
**Issue Type**
[x] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[x] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: Linux
* Browser: Chrome, Firefox

**Description**

It seems the search in the top bar of the docs doesn't work. I see it uses Algolia, so I expect a result box to appear automatically when I type, but nothing happens. If I press enter, the page reloads. I'm not sure when this last worked, but it may just be a matter of configuring Algolia.

**Comment by janpio** [comment]
Work is being done on this via JIRA: https://issues.apache.org/jira/browse/CB-14266

**Comment by Menardi** [comment]
Ah, thanks for the link. I didn't realise issues for the docs were still being reported on JIRA. I'll close this.

**Comment by janpio** [comment]
Issue limbo I would call it ;)

New things should definitely be reported here, but we didn't officially make the switch yet and also didn't publish any instructions, so anything goes.
