### ISSUE TITLE
Documentation search is not working

### ISSUE THREAD

**Issue by shazron** [apache/cordova-docs#874]
**Issue Type**
- [X] Bug
- [ ] Feature Request

**Priority**
- [ ] Minor 
- [X] Major 
- [ ] Critical 
- [ ] Blocker 

**Environment**
https://cordova.apache.org 

* OS:
All

* Browser:
All

**Description**
Users cannot do a documentation search (powered by Algolia) on Cordova's website. This greatly affects use of Cordova.

Original JIRA issue: https://issues.apache.org/jira/browse/CB-14266

**Comment by shazron** [comment]
The doc search has been fixed by Algolia (thanks @s-pace!), but we need to make some changes.
From @s-pace:

- I have updated [your configuration in order to avoid this situation to happen again](https://github.com/algolia/docsearch-configs/commit/1f598ac78525004d0a114ffd7e50ffec364b655c). I have also deployed these changes which are live, you can check it from your website, the search is back.

In order to prevent such behaviour in the future, we would need you to implement some changes from your pages. We do not want to only rely on the URLs itself. Every page's content should have enough context.
- [ ] We would need you to add some meta tags within your html. These tags should be built this way:
```html
<meta name="docsearch:language" content="en">
<meta name="docsearch:version" content="8.x">
```
Please note that the `content` attribute should be equal to the one used from the DocSearch-UI JS snippet. For example on this page:
```javascript
<script type="text/javascript">
docsearch({
apiKey: '0a916ab198bd93d031aa70611271e42e',
indexName: 'cordova',
inputSelector: '#header-search-field',
algoliaOptions: { 'facetFilters': ["version: 8.x", "language: en"] }
});
</script>
```
This is something you can find on the Docusaurus website or Jest (implementing docusaurus) as a detailed example.

- [ ] We would need your sitemap to be updated. It will be our main source of truth in order to discover your website. We didn't detected any issue regarding this sitemap so far.
- [ ] Avoid having pages duplicates pages (e.g. this page and this index.html one). You might want to add a 3XX status to one of both. We avoid such issue by using the stop_urls parameter. This point is solved by preventing crawling the URLs matching the following regex: "https://cordova.apache.org/docs/[^/]+/[^/]+/index.html$"
- [ ] PR your configuration as soon as you are ready with these changes. We will merge it and deploy it once it is live. The current configuration will work with the above changes anyway. You can find the expected configuration enclosed.

**Comment by janpio** [comment]
(Algolia are the best 💯)

**Comment by s-pace** [comment]
Happy to help here 🙏
