### ISSUE TITLE
Fix Slack link

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#897]
Link in the footer seems broken to me. I would favor a more direct pointer to <https://cordova.slack.com/>.

**Comment by janpio** [comment]
The direct link will probably not work as this is for an app to invite yourself to the Slack channel.

But currently it doesn't seem to load at all, so there is definitely something broken.

**Comment by breautek** [comment]
Problem appears to be in the slack library itself...

Stacktrace when interacting with the slack button:

```
Uncaught TypeError: e.data.substr is not a function
    at slackin.js:76
(anonymous) @ slackin.js:76

```
