### ISSUE TITLE
Cordova build android failed.Could not find intellij-core.jar  

### ISSUE THREAD

**Issue by Pakinwet** [apache/cordova-docs#899]
**Issue Type**
[ X ] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[ X ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: Android
* Browser:

**Description**

`
FAILURE: Build failed with an exception.
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar
`

**Comment by dpogue** [comment]
This has also been reported on cordova-android, and the discussion there has some workarounds documented. Please see https://github.com/apache/cordova-android/issues/521 for more details.

Going to close this and try to keep all the discussion in one place :)
