### ISSUE TITLE
CodeSignIdentity in iOS platform guide not correct

### ISSUE THREAD

**Issue by Kezzel** [apache/cordova-docs#900]
**Issue Type**
[x ] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[ x] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: iOS
* Xcode 9.4.1

**Description**
The documentation for iOS platform guideline, states to use codeSignIdentity "Iphone Developer" for both debug and release.
This baffled me a long time and I finally ended up figuring out that it ought to be "Iphone Distribution" when signing a release. 
I am not a wizz and may have misunderstood some of the documentation, however I think it would be beneficial to a lot of users if this part was at least clarified:-)

**Comment by dpogue** [comment]
When using automatic signing for iOS (which we try to encourage), you do need to use "iPhone Developer" for both debug and release.

If you're doing manual signing, you should be able to leave `codeSignIdentity` out of build.json entirely, and instead specify the `provisioningProfile` as a UUID. If you don't override it, we use "iPhone Distribution" for signing release builds.
