### ISSUE TITLE
Document how to create from tarball

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#903]
From <https://github.com/apache/cordova/issues/32#issuecomment-436284518> I found out that it is possible to run `./bin/create` from a platform tarball, if I am not mistaken.

I think this should be documented explicitly, which I did not see.

Also how to use `bin\create.bat` on Windows cmd.

**Comment by dpogue** [comment]
It is documented, see the "Platform Centered Workflow" section in each platform's documentation:
* [Android](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#platform-centered-workflow)
* [iOS](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#platform-centered-workflow)
* [Windows](https://cordova.apache.org/docs/en/latest/guide/platforms/windows/index.html#platform-centered-workflow)
