### ISSUE TITLE
Document cordova-lib API

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#912]
**Issue Type**
[ ] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: all
* Browser: all

**Description**

Tools such as <https://github.com/dpa99c/cordova-check-plugins> should be able to use `cordova-lib` more programmatically rather than having to spawn a hopefully updated version of the Cordova CLI. I did not see where the `cordova-lib` API is documented though.

**Comment by marti1125** [comment]
Hi @brodybits  I would like to contribute with this issue, could you give me some advices?

**Comment by brodybits** [comment]
I suggest you start by reading through the cordova-cli code to understand how cordova-lib works. You should also take a look at how pages on cordova.apache.org are generated from cordova-docs.

I cannot promise when I can give you any better advice on this. To document this properly would likely require some knowledge of how cordova-common and cordova-lib work internally. It may be helpful if you want to start modernizing some of the code to use ES6 features.

In terms of documenting I would suggest looking for easier tasks first.

I am extremely busy with commitments and I think others are as well. I think you would have a better chance of getting help if you would start with easier tasks and more specific questions. I would also suggest you request help from <dev@cordova.apache.org>.

**Comment by janpio** [comment]
The correct place to document cordova-lib would be at https://github.com/apache/cordova-lib - this is not an end user facing part in any way. If this documentation was added, it might be worth adding a mention and link to the normal documentation though.
