### ISSUE TITLE
Properly translate paragraph into German

### ISSUE THREAD

**Issue by kputh** [apache/cordova-docs#932]
**Issue Type**
[✓] Bug
[ ] Feature Request

**Priority**
[✓] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Description**

<img width="1280" alt="ios_platform_guide_-_apache_cordova" src="https://user-images.githubusercontent.com/8649002/52415080-5f3a1f00-2ae6-11e9-8c06-a7227531b63c.png">

from https://cordova.apache.org/docs/de/8.x/guide/platforms/ios/index.html

_Comman-Netzanschlussklemme führen_ is not German, its gibberish.

**Comment by janpio** [comment]
Wir sind immer offen für Pull Requests, allerdings muss ich dabei fairerweise anmerken, dass noch nicht klar ist wie mit den (schrecklichen und auch veralteten) Übersetzungen in der Zukunft verfahren wird.

**Comment by jcesarmobile** [comment]
We are removing the translations, so this won’t be fixed
