### ISSUE TITLE
[Documentation] indexedDb on iOS

### ISSUE THREAD

**Issue by mesqueeb** [apache/cordova-docs#948]
The current documentation on [indexedDb](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#disadvantages) says:
> Disadvantages
> - Not supported on iOS.

**Is this really still the case?**

Because according to the Dexie library it has already implemented indexedDB 2.0...
See: [Dexie.org - IndexedDB on Safari](https://dexie.org/docs/IndexedDB-on-Safari)

**Comment by dpogue** [comment]
indexedDB is properly supported by both WKWebView and UIWebView as of iOS 10.3.

**Comment by mesqueeb** [comment]
Should I make a pr on the cordova docs?

**Comment by erisu** [comment]
Has been resolved
