### ISSUE TITLE
Sections titles with apostrophes do not link correctly

### ISSUE THREAD

**Issue by GedasGa** [apache/cordova-docs#954]
# Bug Report

## Problem

In the Electron's documentation section, if in the navigation bar you click on the "Customizing the Application's Window Process" or on the "Customizing the Electron's Main Process" it won't link you to the appropriate section.

### What is expected to happen?

It is expected that once you click on any section in the navbar, it should link you to the appropriate section in the documentation.

### What does actually happen?

Nothing happens. The user remains in the same section.

### Information

The problem is related to the name of the section and how we build an HTML document from `.md` files. When we build an HTML document, we take the names of the headings from the `.md` file and create an anchor tag for every 2nd layer (`##`) heading.

For instance:
```
<a class="fragment-anchor" id="customizing-the-electron's-main-process"></a>
```

We use heading's name as an `id` of the element in the navbar link as well as the document, in this case, `./docs/en/latest/guide/platforms/electron/index.html`.

Since both section names "Customizing the Application's Window Process" and "Customizing the Electron's Main Process" contain an apostrophe, we also happen to use an apostrophe in the `id`. Unfortunately, this is what causes this issue.

### Possible solutions

- First and the simplest - change the name of the section.
- Manually edit the `id` of the corresponding element it in the `./docs/en/latest/guide/platforms/electron/index.html` and `href` of `<a>` element in the navbar
- Use the backslash (`\`) to escape the apostrophe symbol in the `href` of `<a>` element in the navbar

### Environment, Platform, Device

I believe this problem is across all the browsers and operating systems since they all build HTML in a similar way. I've successfully reproduced the problem on the newest Chrome and Safari browsers on macOS.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to the most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Nice catch.
I think changing the titles to something like these will be good:
- **Customizing Application Window**
- **Customizing Main Process**

**Comment by GedasGa** [comment]
Thanks! Sure, sounds good. I'll go ahead and make these changes!
