### ISSUE TITLE
buildAndDeploy.sh does not fail Travis CI build when something goes wrong

### ISSUE THREAD

**Issue by janpio** [apache/cordova-docs#981]
https://github.com/apache/cordova-docs/issues/959 shows that a failure during the deploy process via https://github.com/apache/cordova-docs/blob/master/buildAndDeploy.sh does not fail the build if something goes wrong.

Example:
"Successful" build at:
https://travis-ci.org/apache/cordova-docs/builds/529733608?utm_source=github_status&utm_medium=notification
If actually look at the raw log:
https://api.travis-ci.org/v3/job/529733609/log.txt
You see this:
```
svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Commit failed (details follow):
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```

So clearly the `svn commit` actually failed, but the failure was not reported to Travis to alert us about this problem.

**Comment by raphinesse** [comment]
She never responded to a mention as long as I've been around. So I'd say just drop it. We will notice when something breaks.

**Comment by janpio** [comment]
Problem is that this being the release process, it's pretty hard/cumbersome to debug.

**Comment by janpio** [comment]
Yeah, the build definitely takes 20 minutes and longer (24 for the last few).

No comment about motivation of extraction to shell script in https://issues.apache.org/jira/browse/CB-13543 as well. (Are you around @audreyso and can give some insight maybe?)

**Comment by dblotsky** [comment]
Seems like the return code of `buildAndDeploy.sh` might be ignored. Can you verify if that's the case?
