### ISSUE TITLE
How to use with JavaScript tools such as Webpack ...

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#983]
... Babel, Rollup, tsc (TypeScript compiler), etc. etc.

... should include pointers to integration with other tools such as eslint, Prettier, tslint, vscode

## Motivation Behind Feature

The larger JavaScript web ecosystem has plenty of nice dev tooling, but I think the integration with Cordova is not always 100% intuitive and could be much better documented.

## Feature Description

- Document how devs would normally use Cordova together with tools such as Webpack and other tools listed above, at minimum:
  - introductory guide
  - pointer to recommended resources
  - document anything that may need to be done differently due to the use of the Cordova framework

## Alternatives or Workarounds

- Q&A on StackOverflow

**Comment by dpogue** [comment]
My thought is that there shouldn't be any special (or any, at all) integration between these tools and Cordova.

The job of the tools is to compile whatever you're working with into a www folder.
The job of Cordova is to package up that www folder into native app projects.

Many of the issues that people have with Cordova stem from poorly designed attempts to integrate Cordova into framework tools, and then people find themselves stuck on old unsupported versions.

**Comment by janpio** [comment]
A blog post "How to use 'JavaScript tools such as Webpack' on your Cordova web app" might work around this. It could give people some pointers how this stuff works, without the need for us to keep the list of tools, the version, the instructions etc super updated as it would be if we add this to the docs.

Alternative this could be published somewhere else, and we just add a "Community Resources" section to the docs where we curate such links.

**Comment by jcesarmobile** [comment]
I agree with dpogue, not something we have to document, as janpio said, better link an external blog post we don’t have to maintain.
Most people that uses we pack and similar tooling is because the framework they use uses it and it’s handled by them.
