### ISSUE TITLE
Document use with WebAssembly

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-docs#984]
# Feature Request

## Motivation Behind Feature

The JavaScript ecosystem is increasingly using WebAssembly. I can think of the following potential pitfalls:

- support for WebAssembly features may not be consistent on all existing and future platforms (see apache/cordova#100 for an example)
- integration of tooling with Cordova does not seem to be tested or documented (see #983)

## Feature Description

- document that use with WebAssembly is dependent on which WebView is used (#943)
- document integration and any potential pitfalls in terms of wasm tooling (#983)

I will understand if this issue is closed as a duplicate, still think it is valid.

## Alternatives or Workarounds

- discuss on mail list
- StackOverflow

**Comment by janpio** [comment]
This could maybe solved via a "State of Cordova and Web Assembly" blog post.

**Comment by breautek** [comment]
Like with pretty much every other web feature, it's going to be completely reliant on the underlying webview. I don't really see a need to explicitly document on web assembly.

Web Assembly even today is still pretty primitive and hard to make real practical use of (and I'm speaking as someone who has been researching ways to render 100,000s of features on a rendered map more efficiently).

Closing as stale.
