### ISSUE TITLE
Docs should specify exact dependencies or use shrinkwrap.

### ISSUE THREAD

**Issue by dblotsky** [apache/cordova-docs#993]
# Feature Request

## Motivation Behind Feature
If a dependency in the docs changes, npm will install it automatically on your machine. To avoid this, we should pin docs dependencies to specific versions.

## Feature Description
Pin docs dependencies to specific versions.

## Alternatives or Workarounds
1. Specify exact version numbers in `package.json`.
2. Specify a `npm-shrinkwrap.json` file.
3. Specify a `package-lock.json` file.

**Comment by breautek** [comment]
We have `package-lock.json` committed now which should address the original concern.
