### ISSUE TITLE
Missing Documentation for Accessing Network Attached Storage

### ISSUE THREAD

**Issue by wwwizzarrdry** [apache/cordova-docs#996]
Missing documentation for connecting an Android application to a local network share. 

Eg. There is no information regarding how to read/write to a local samba share at  smb://server-name/folder-name, and fallback to internal storage when unavailable.

**Comment by brodybits** [comment]
I think this request is outside the scope of Cordova.

**Comment by wwwizzarrdry** [comment]
Is that because this is a limitation of Android? Seems strange that I can't find any documentation for mounting samba shares in any Android docs anywhere, including Cordova. Android only seems capable of accessing local and removable storage, can that really be the case?

**Comment by breautek** [comment]
Realise this is old but I don't believe Android has a samba protocol implementation. So if you wanted to use samba on android, you'll need to install some file manager app that implements the samba protocol.

Of course, one could implement the samba protocol as a form of a cordova plugin to add support for samba as well, but I agree, this is out of scope of Cordova. There may be existing plugins available that provides a samba implementation.

**Comment by breautek** [comment]
Closing as obsolete.
